server:
  port: 8080

spring:
  application:
    name: "HesTestTask"
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        hibernate.default_schema: hes
        globally_quoted_identifiers: true
        show_sql: true
        format_sql: true
        jdbc:
          lob:
            non-contextual-creation: true
  liquibase:
    change-log: classpath:/db/changelog/app-changelog.yml
    default-schema: hes
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: sA#259979148307

preliquibase:
  sqlScriptReferences: classpath:/db/preliquibase/create_schema.sql

logging:
  level:
    org:
      springframework:
        security: trace
        transaction:
          interceptor: trace
    root: INFO
  file:
    path: src/main/resources/logs
    name: src/main/resources/logs/resource-service.log

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  show-actuator: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

info:
  application:
    name: ${spring.application.name}
    description: HES test task
